services:
  - type: web
    name: floppa-chatbot
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
